

import type { Metadata } from "next";
import Head from "next/head";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Whatsapp from "@/components/button-whats";
import { Footer } from "@/components/footer";
import NavbarClassic from "@/components/navbar-clasic";


const UbuntuFont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Diamond King",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <Head>
         <meta name="theme-color" content="#000"/>
      </Head>   
      <body className={`${UbuntuFont.className}  antialiased relative fade`}>
        <NavbarClassic/>
        {children}
        <Whatsapp />
        <Footer />
      </body>
    </html>
  );
}
