import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const UbuntuFont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"], // 👈 agregado
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${UbuntuFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
