import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Whatsapp from "@/components/button-whats";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";

const UbuntuFont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"], // 👈 agregado
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${UbuntuFont.className} fade-in antialiased relative`}>
        <Navbar>HOla como estas</Navbar>
      
        {children}
        <Whatsapp />
        <Footer />
      </body>
    </html>
  );
}
